#!/bin/bash
#DATA_ROOT=imgs/frames_wallenstein_blurry_512/AB/ name=wildeJagd2_512 which_direction=BtoA gpu=0 cudnn=0 loadSize=512 fineSize=512 continue_train=1 th train.lua
DATA_ROOT=/inputImages/AB name=wildeJagd_wallenstein_512_blurry which_direction=BtoA gpu=0 cudnn=0 loadSize=512 fineSize=512 continue_train=0 th train.lua