#!/bin/bash
dir=$1
cd $dir
mkdir train
mkdir test
mkdir val
mv *.png train
for file in `find ./train -type f | awk 'NR %4 == 0'`; do mv $file test ; done
for file in `find ./train -type f | awk 'NR %5 == 0'`; do mv $file val ; done
cd -